colorscheme gruvbox-dark

# indentaion options
set-option global tabstop     4
set-option global indentwidth 4

hook global InsertChar \t %{
    exec -draft h@
}

# plugin manager and plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload
plug "alexherbo2/auto-pairs.kak"
plug 'delapouite/kakoune-buffers' %{
    map global normal ^ q
    map global normal <a-^> Q
    map global normal q b
    map global normal Q B
    map global normal <a-q> <a-b>
    map global normal <a-Q> <a-B>
    map global normal b ': enter-buffers-mode<ret>' -docstring 'buffers'
    map global normal B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)'
}

# auto pairs config
set-option global auto_pairs ( ) { } [ ] '"' '"' "'" "'" ` ` │ “ ” ‘ ’ « » ‹ ›
evaluate-commands enable-auto-pairs

# kakoune-buffers aliases
alias global buf info-buffers
alias global bd delete-buffer
alias global bf buffer-first
alias global bl buffer-last
alias global bo buffer-only
alias global bo! buffer-only-force
